server:
  port: 8585

spring:
  application:
    name: bike-service

  config:
    import: "optional:classpath:secret.properties"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/wigell-realm

  datasource:
    url: jdbc:mysql://localhost:3306/wigell_mc_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: admin
        instance:
          prefer-ip: true
          management-base-url: http://localhost:8585

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

keycloak:
  auth-server-url: http://localhost:8090 # Samma bas som din issuer-uri
  realm: wigell-realm
  client-id: wigell-superadmin
  client-secret: ${my.secret.value}

services:
  currency-converter:
    url: http://localhost:8080/currency/api/v1/currency/convert